# from yacs.yacs_config import CfgNode as CN
import os.path as osp

from yacs.config import CfgNode as CN

_C = CN()
_C.TASK = ""
_C.DATA_TABLE = ""
_C.FOLD_SPLIT = ""
_C.NUM_FOLD = 5
_C.LOG_FILE = ""
_C.LABEL_NAME = "Label"
_C.MULTI_LABEL = False

# PATCH
_C.PATCH = CN()
_C.PATCH.IDX2IMG = ""

# PRETRAIN
_C.PRETRAIN = CN()
_C.PRETRAIN.MODEL_NAME = ""
_C.PRETRAIN.MODEL_PATH = ""
_C.PRETRAIN.SAVE_DIR = ""
_C.PRETRAIN.SAVE_DIR_COMBINED = ""
_C.PRETRAIN.TRAIN_FEA_TIMES = 5
_C.PRETRAIN.NUM_CLASSES = 2

# MODEL
_C.MODEL = CN()
_C.MODEL.MODEL_NAME = ""

# # # for transformer
_C.MODEL.POSITION_EMBEDDING = ""
_C.MODEL.HIDDEN_DIM = 1
_C.MODEL.NUM_INPUT_CHANNELS = 1
_C.MODEL.NUM_CLASSES = 2
_C.MODEL.LR_BACKBONE_NAME = []  
_C.MODEL.LR_LINEAR_PROJ_NAME = []
_C.MODEL.N_HEADS = 8
_C.MODEL.ENCODER_LAYERS = 4
_C.MODEL.DECODER_LAYERS = 2

# MODEL_VIT
_C.MODEL_VIT = CN()
_C.MODEL_VIT.NUM_CLASSES = 2
_C.MODEL_VIT.DROPOUT = 0.5
_C.MODEL_VIT.NUM_INPUT_CHANNELS = 1280
_C.MODEL_VIT.HIDDEN_DIM = 256
_C.MODEL_VIT.DEPTH = 6
_C.MODEL_VIT.HEADS = 16
_C.MODEL_VIT.MLP_DIM = 256

# MODEL_VILT
_C.MODEL_VILT = CN()
_C.MODEL_VILT.LOSS_NAMES = ["gene"]  # "itm": 1, "mlm": 1
_C.MODEL_VILT.NUM_CLASSES = 2
_C.MODEL_VILT.TASKS = ["gene"]
# Image Setting
_C.MODEL_VILT.MAX_IMG_LEN = 1280
_C.MODEL_VILT.MAX_TEXT_LEN = 1
# Transformer Setting
_C.MODEL_VILT.VIT = "vit_block_only"
_C.MODEL_VILT.HIDDEN_SIZE = 768
_C.MODEL_VILT.DROP_RATE = 0.1
_C.MODEL_VILT.DEPTH = 12
_C.MODEL_VILT.NUM_HEADS = 12
_C.MODEL_VILT.RE_ATTENTION = False
_C.MODEL_VILT.DISTILLED = False
_C.MODEL_VILT.TABNET_EMBEDDING = False

# DATASET
_C.DATASET = CN()
_C.DATASET.DATASET_NAME = ""
_C.DATASET.DATASET_SEED = 1
_C.DATASET.DATASET_SCALE = "x20"
_C.DATASET.PATCH_SCORE_PATH = "./"
_C.DATASET.PATCH_TOP_K_METHOD = (
    "random"  # random score, tissue, patch_level_pretrained, contrastive_learning
)
_C.DATASET.FEATURE_LEN = 150
_C.DATASET.FEATURE_MAP_SIZE = 60  
_C.DATASET.TABLE_DATA = "./table.csv"
_C.DATASET.FEATURE_NAMES = []
_C.DATASET.TABULAR_NUM = 21
_C.DATASET.NUM_PROTOTYPES = 10
_C.DATASET.INTER_FACTOR = 0.5
_C.DATASET.LOAD_PATH = (
    "."
)
_C.DATASET.LOAD_CLU = True
_C.DATASET.PATCH_LEVEL = False

# TRAIN
_C.TRAIN = CN()
_C.TRAIN.SEED = 1
_C.TRAIN.MAX_PATIENCE = 50
_C.TRAIN.EPOCHS = 10000
_C.TRAIN.START_EPOCH = 0
_C.TRAIN.BATCH_SIZE = 2
_C.TRAIN.NUM_WORKERS = 0
_C.TRAIN.LR = 1e-3
_C.TRAIN.LR_BACKBONE = 1e-3
_C.TRAIN.LR_LINEAR_PROJ_MULT = 0.1
_C.TRAIN.WEIGHT_DECAY = 1e-4
_C.TRAIN.LR_DROP = 40
_C.TRAIN.CLIP_MAX_NORM = 0.01
_C.TRAIN.OPTIM_NAME = "sgd"
_C.TRAIN.LOSS_NAME = "focal"
_C.TRAIN.EVAL = False
_C.TRAIN.RESUME_PATH = ""
_C.TRAIN.OUTPUT_DIR = ""
_C.TRAIN.CACHE_MODE = False
_C.TRAIN.EMA = 0.95
_C.TRAIN.WARMUP = 5
# for vilt
_C.TRAIN.TEST_ONLY = False
# for metrix
_C.TRAIN.KAPPA = False


def get_cfg_defaults():
    """Get a yacs CfgNode object with default values for my_project."""
    # Return a clone so that the defaults will not be altered
    # This is for the "local variable" use pattern
    return _C.clone()


def update_default_cfg(cfg):
    """
    Args:
        cfg ([type]): [description]
    """
    cfg.TRAIN.OUTPUT_DIR = osp.join(cfg.TRAIN.OUTPUT_DIR, f"label-{cfg.LABEL_NAME}")
    cfg.FOLD_SPLIT = osp.join(cfg.TRAIN.OUTPUT_DIR, f"fold_split")
